import React from 'react';

const Terms = () => {
        return (
            <div>
            <h2 className="subheader">PERSONAL LOANS</h2>
            <div className="container">
                Variable rates from [_]% APR to [_]% APR (with AutoPay). ProFormance Management Group, LLC (“ProFormance”) rate ranges are current as of November 7, 2018 and are subject to change without notice. Not all rates and amounts available in all states. Only those persons who are eligible to obtain a loan from ProFormance may do so. Not all applicants qualify for the lowest rate. If approved for a loan, to qualify for the lowest rate, you must have a responsible financial history and meet other conditions. Your actual rate will be within the range of rates listed above and will depend on a variety of factors, including evaluation of your credit worthiness, years of professional experience, income and other factors. See APR examples and terms. Interest rates on variable rate loans are capped at [_]%. Lowest variable rate of [_]% APR assumes current Prime Rate of 5.25% plus [_]% margin minus 0.25% AutoPay discount plus an origination fee of $[_]. For the ProFormance variable rate loan, the Prime Rate index will adjust monthly and the loan payment may change monthly. APRs for variable rate loans may increase after origination if the Prime Rate index increases. The ProFormance 0.25% AutoPay interest rate reduction requires you to agree to make monthly principal and interest payments by an automatic monthly deduction from a savings or checking account. The benefit will discontinue and be lost for periods in which you do not pay by automatic deduction from a savings or checking account. Terms and Conditions Apply. PROFORMANCE RESERVES THE RIGHT TO MODIFY OR DISCONTINUE PRODUCTS AND BENEFITS AT ANY TIME WITHOUT NOTICE. To qualify, a borrower must be a U.S. citizen or permanent resident in an eligible state and meet ProFormance's underwriting requirements. Not all borrowers receive the lowest rate. To qualify for the lowest rate, you must have a responsible financial history and meet other conditions. If approved, your actual rate will be within the range of rates listed above and will depend on a variety of factors, including term of loan, a responsible financial history, years of experience, income and other factors. Rates and Terms are subject to change at anytime without notice and are subject to state restrictions. ProFormance refinance loans are private loans and do not have the same repayment options that the federal loan program offers such as Income Based Repayment or Income Contingent Repayment or PAYE. Licensed by the Department of Business Oversight under the California Financing Law License No. [_]. ProFormance loans are originated by Proformance Management Group, LLC., NMLS # [_]. (www.nmlsconsumeraccess.org)
             </div>
        </div>
      );
    
   }

export default Terms;